version: '3'
services:
  # rest_users:
  #   image: postgrest/postgrest
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     PGRST_DB_URI: postgresql://postgres:i6FofFBK737oF3E1EafO@containers-us-west-128.railway.app:7036/railway
  #     PGRST_OPENAPI_SERVER_PROXY_URI: http://0.0.0.0:3000
  #     PGRST_DB_ANON_ROLE: postgres
  # rest_degrees:
  #   image: postgrest/postgrest
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     PGRST_DB_URI: postgresql://postgres:i6FofFBK737oF3E1EafO@containers-us-west-128.railway.app:7036/railway
  #     PGRST_OPENAPI_SERVER_PROXY_URI: http://0.0.0.0:3000
  #     PGRST_DB_ANON_ROLE: postgres
  # rest_courses:
  #   image: postgrest/postgrest
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     PGRST_DB_URI: postgresql://postgres:i6FofFBK737oF3E1EafO@containers-us-west-128.railway.app:7036/railway
  #     PGRST_OPENAPI_SERVER_PROXY_URI: http://0.0.0.0:3000
  #     PGRST_DB_ANON_ROLE: postgres
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.worker
      args:
        WORKER: gateway
    container_name: gateway
    volumes:
      - ./workers/gateway:/usr/src/app/workers/gateway
    ports:
      - "60000:8787"
