version: '3'
services:
  db_gateway:
    build:
      context: ./scripts-db-dev
      dockerfile: Dockerfile
      args:
        DB: gateway
    container_name: mesw-cosn-db_gateway
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
  rest_gateway:
    image: postgrest/postgrest
    container_name: mesw-cosn-rest_gateway
    environment:
      PGRST_DB_URI: postgres://app_user:password@db_gateway:5432/app_db
      # PGRST_DB_ANON_ROLE: postgres
      PGRST_DB_ANON_ROLE: app_user
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.worker
      args:
        WORKER: gateway
    container_name: mesw-cosn-gateway
    volumes:
      - ./workers/gateway:/usr/src/app/workers/gateway
    ports:
      - "60000:8787"
