export enum DegreeStatusEnum {
  IN_PROGRESS = "IN_PROGRESS",
  ARCHIVED = "ARCHIVED",
}

export enum EqfLevelEnum {
  EARLY_EDUCATION = "EARLY_EDUCATION",
  PRIMARY_EDUCATION = "PRIMARY_EDUCATION",
  LOWER_SECONDARY = "LOWER_SECONDARY",
  UPPER_SECONDARY = "UPPER_SECONDARY",
  POST_SECONDARY = "POST_SECONDARY",
  SHORT_CYCLE = "SHORT_CYCLE",
  BACHELOR = "BACHELOR",
  MASTER = "MASTER",
  DOCTORAL = "DOCTORAL",
  NOT_DEFINABLE = "NOT_DEFINABLE",
}
