name = "cosn-users"
main = "src/index.ts"
compatibility_date = "2022-11-04"
account_id = "6cac6bb74225f44bf6842d3c8cf604e9"

[vars]
ENV = "development"
DATABASE_ENDPOINT = "http://users_db_rest:3000"
JWT_SECRET = "qwerty123"

[env.production.vars]
ENV = "production"
DATABASE_ENDPOINT = "https://dbrest-production-1a83.up.railway.app"
