FROM node:16
RUN npm install --global pnpm
WORKDIR /usr/src/app
COPY pnpm-lock.yaml .
COPY pnpm-workspace.yaml .
RUN pnpm fetch
COPY package.json .
COPY tsconfig.base.json .
ARG WORKER
COPY ./workers/$WORKER ./workers/$WORKER
RUN pnpm install
WORKDIR /usr/src/app/workers/$WORKER
CMD pnpm dev
