name = "cosn-courses"
main = "src/index.ts"
compatibility_date = "2022-11-04"
account_id = "6cac6bb74225f44bf6842d3c8cf604e9"

[vars]
ENV = "development"
DATABASE_ENDPOINT = "http://courses_db_rest:3000"

[env.production.vars]
ENV = "production"
