name = "cosn-courses"
main = "src/index.ts"
compatibility_date = "2022-11-04"
account_id = "6cac6bb74225f44bf6842d3c8cf604e9"

[env.production]
name = "cosn-courses"

[env.production.vars]
ENV = "production"
DATABASE_ENDPOINT = "https://dbrest-production-3182.up.railway.app"
