name = "cosn-degrees"
main = "src/index.ts"
compatibility_date = "2022-11-04"
account_id = "6cac6bb74225f44bf6842d3c8cf604e9"

[env.production]
name = "cosn-degrees"

[env.production.vars]
ENV = "production"
DATABASE_ENDPOINT = "https://dbrest-production-822a.up.railway.app"
KAFKA_PROXY_ENDPOINT = "http://kafka_proxy:4000"
